#ifndef _IDENTIFY_DEVICE_H
#define	_IDENTIFY_DEVICE_H

#define	LPA_SUPPORT_NS_BASED_SMART_LOG		1
#define	LPA_SUPPORT_COMMAND_EFFECTS_LOG		1
#define	LPA_SUPPORT_EXTENDED_DATA		1
#define	LPA_SUPPORT_TELEMETRY			0

#define	IDFY_LPA					(\
	(LPA_SUPPORT_NS_BASED_SMART_LOG		<< 0)	|\
	(LPA_SUPPORT_COMMAND_EFFECTS_LOG	<< 1)	|\
	(LPA_SUPPORT_EXTENDED_DATA		<< 2)	|\
	(LPA_SUPPORT_TELEMETRY			<< 3)	)

#define	FRMW_FW_SLOT1_READONLY			0
#define	FRMW_NUMBER_OF_FW_SLOTS			1
#define	FRMW_SUPPORT_IMMEDIATE_FW_ACTIVATION	0

#define IDFY_FRMW					(\
	(FRMW_FW_SLOT1_READONLY			<< 0)	|\
	(FRMW_NUMBER_OF_FW_SLOTS		<< 1)	|\
	(FRMW_SUPPORT_IMMEDIATE_FW_ACTIVATION	<< 4)	)

BOOL Device_Identify(NVME_QID sqid, NVME_QID cqid);

#endif	/* _IDENTIFY_DEVICE_H */

