/******************************************************************************
** File Name: ATA_Vars.h
** Author:
** Creation Time: Sun Nov 26 20:49:34 2017
*/
#ifndef	_ATA_VARS_H
#define	_ATA_VARS_H

#define	ATA_Field(x)	gATA_Fields.x

#define	BIT(x)		(1u << (x))
#define	BMP_BITS	32

#define	BMP_DEFINE(var, bits)	BMP var[((bits) + BMP_BITS - 1) / BMP_BITS]

typedef	unsigned int	BMP;

extern	BMP	gATA_Bits[];

static inline void ATA_BitClr(int index)
{
	int	w = index / BMP_BITS;
	int	b = index % BMP_BITS;

	gATA_Bits[w] &= ~BIT(b);
}

static inline void ATA_BitSet(int index)
{
	int	w = index / BMP_BITS;
	int	b = index % BMP_BITS;

	gATA_Bits[w] |= BIT(b);
}

static inline unsigned int ATA_BitGet(int index)
{
	int	w = index / BMP_BITS;
	int	b = index % BMP_BITS;

	return (gATA_Bits[w] >> b) & 1;
}

enum {
	bit_28BIT_SUPPORTED,
	bit_48BIT_SUPPORTED,
	bit_ABO_FOREGROUND_MODE_SUPPORTED,
	bit_ABO_IR_MODE_SUPPORTED,
	bit_ACS3_COMMANDS_ALLOWED_BY_SANITIZE,
	bit_ADVANCED_BACKGROUND_OPERATION_SUPPORTED,
	bit_APM_ENABLED,
	bit_APM_SUPPORTED,
	bit_AUTOMATIC_PARTIAL_TO_SLUMBER_TRANSITIONS_ENABLED,
	bit_AMAX_ADDR_SUPPORTED,
	bit_BLOCK_ERASE_SUPPORTED,
	bit_CRYPTO_SCRAMBLE_SUPPORTED,
	bit_DATA_SET_MANAGEMENT_XL_SUPPORTED,
	bit_DATE_TIME_RATE_BASIS_SUPPORTED,
	bit_DEFINITIVE_ENDING_PATTERN_SUPPORTED,
	bit_DEVICE_AUTOMATIC_PARTIAL_TO_SLUMBER_TRANSITIONS_SUPPORTED,
	bit_DEVICE_INITIATED_POWER_MANAGEMENT_ENABLED,
	bit_DEVICE_INITIATED_POWER_MANAGEMENT_SUPPORTED,
	bit_DEVICE_SLEEP_ENABLED,
	bit_DEVICE_SLEEP_SUPPORTED,
	bit_DEVSLEEP_TO_REDUCEDPWRSTATE_CAPABILITY_SUPPORTED,
	bit_DEVSLP_TIMING_VARIABLES_SUPPORTED,
	bit_DLC_ENABLED,
	bit_DLC_SUPPORTED,
	bit_DM_CLEARS_NONACTIVATED_DEFERRED_DATA,
	bit_DM_IMMEDIATE_SUPPORTED,
	bit_DM_MODE3_SUPPORTED,
	bit_DM_OFFSETS_DEFERRED_SUPPORTED,
	bit_DM_OFFSETS_IMMEDIATE_SUPPORTED,
	bit_DMA_SETUP_AUTO_ACTIVATION_ENABLED,
	bit_DMA_SETUP_AUTO_ACTIVATION_SUPPORTED,
	bit_DMA_SUPPORTED,
	bit_DOWNLOAD_MICROCODE_DMA_SUPPORTED,
	bit_DOWNLOAD_MICROCODE_SUPPORTED,
	bit_DRAT_SUPPORTED,
	bit_DSN_ENABLED,
	bit_DSN_SUPPORTED,
	bit_ENCRYPT_ALL_SUPPORTED,
	bit_ENHANCED_SECURITY_ERASE_SUPPORTED,
	bit_ENHANCED_SECURITY_ERASE_TIME_FORMAT,
	bit_EPC_ENABLED,
	bit_EPC_SUPPORTED,
	bit_ExtendedNumberOfUserAddressableSectorsSupported,
	bit_FLUSH_CACHE_EXT_SUPPORTED,
	bit_FREE_FALL_ENABLED,
	bit_FREE_FALL_SUPPORTED,/*
	bit_FW_ACTIVATION_PENDING,*/
	bit_GPL_DMA_SUPPORTED,
	bit_GPL_SUPPORTED,
	bit_HARDWARE_FEATURE_CONTROL_IS_ENABLED,
	bit_HARDWARE_FEATURE_CONTROL_SUPPORTED,
	bit_HOST_AUTOMATIC_PARTIAL_TO_SLUMBER_TRANSITIONS_SUPPORTED,
	bit_HYBRID_INFORMATION_ENABLED,
	bit_HYBRID_INFORMATION_SUPPORTED,
	bit_IN_ORDER_DATA_DELIVERY_ENABLED,
	bit_IN_ORDER_DATA_DELIVERY_SUPPORTED,
	bit_IORDY_DISABLE_SUPPORTED,
	bit_IORDY_SUPPORTED,
	bit_LOGICAL_SECTOR_SIZE_SUPPORTED,
	bit_LOGICAL_TO_PHYSICAL_SECTOR_RELATIONSHIP_SUPPORTED,
	bit_LOW_POWER_STANDBY_SUPPORTED,
	bit_LPS_MISALIGNMENT_REPORTING_SUPPORTED,
	bit_MASTER_PASSWORD_CAPABILITY,
	bit_MULTIWORD_DMA_MODE0_ENABLED,
	bit_MULTIWORD_DMA_MODE0_SUPPORTED,
	bit_MULTIWORD_DMA_MODE1_ENABLED,
	bit_MULTIWORD_DMA_MODE1_SUPPORTED,
	bit_MULTIWORD_DMA_MODE2_ENABLED,
	bit_MULTIWORD_DMA_MODE2_SUPPORTED,
	bit_NCQ_AUTOSENSE_SUPPORTED,
	bit_NCQ_FEATURE_SET_SUPPORTED,
	bit_NCQ_PRIORITY_INFORMATION_SUPPORTED,
	bit_NCQ_QUEUE_MANAGEMENT_COMMAND_SUPPORTED,
	bit_NCQ_STREAMING_SUPPORTED,
	bit_NON_DATA_CLOSE_ZONE_EXT_SUPPORTED,
	bit_NON_DATA_FINISH_ZONE_EXT_SUPPORTED,
	bit_NON_DATA_OPEN_ZONE_EXT_SUPPORTED,
	bit_NON_DATA_RESET_WRITE_POINTERS_EXT_SUPPORTED,
	bit_NON_VOLATILE_WRITE_CACHE,
	bit_NONZERO_BUFFER_OFFSETS_ENABLED,
	bit_NONZERO_BUFFER_OFFSETS_SUPPORTED,
	bit_NOP_SUPPORTED,
	bit_NORMAL_SECURITY_ERASE_TIME_FORMAT,
	bit_OVERWRITE_SUPPORTED,
	bit_PERSISTENT_SENSE_DATA_REPORTING,
	bit_PIO_MODE3_IS_SUPPORTED,
	bit_PIO_MODE4_IS_SUPPORTED,
	bit_POWER_DISABLE_FEATURE_ALWAYS_ENABLED,
	bit_POWER_DISABLE_FEATURE_ENABLED,
	bit_POWER_DISABLE_FEATURE_SUPPORTED,
	bit_POWER_ON_HOURS_RATE_BASIS_SUPPORTED,
	bit_PUIS_ENABLED,
	bit_PUIS_SUPPORTED,
	bit_READ_BUFFER_DMA_SUPPORTED,
	bit_READ_BUFFER_SUPPORTED,
	bit_READ_LOG_DMA_EXT_AS_EQUIVALENT_TO_READ_LOG_EXT_SUPPORTED,
	bit_READ_LOOK_AHEAD_ENABLED,
	bit_READ_LOOK_AHEAD_SUPPORTED,
	bit_REBUILD_ASSIST_ENABLED,
	bit_REBUILD_ASSIST_SUPPORTED,
	bit_RECEIPT_OF_HOST_INITIATED_POWER_MANAGEMENT_REQUESTS_SUPPORTED,
	bit_REPORT_ZONES_EXT_SUPPORTED,
	bit_REQUEST_SENSE_DEVICE_FAULT_SUPPORTED,
	bit_RESTRICTED_SANITIZE_OVERRIDES_SECURITY,
	bit_REVERTING_TO_DEFAULTS_ENABLED,
	bit_RZAT_SUPPORTED,
	bit_SANITIZE_ANTIFREEZE_LOCK_SUPPORTED,
	bit_SANITIZE_SUPPORTED,
	bit_SATA_GEN1_SIGNALING_SPEED_SUPPORTED,
	bit_SATA_GEN2_SIGNALING_SPEED_SUPPORTED,
	bit_SATA_GEN3_SIGNALING_SPEED_SUPPORTED,
	bit_SATA_PHY_EVENT_COUNTERS_LOG_SUPPORTED,
	bit_SCT_DATA_TABLES_SUPPORTED,
	bit_SCT_ERROR_RECOVERY_CONTROL_SUPPORTED,
	bit_SCT_FEATURE_CONTROL_SUPPORTED,
	bit_SCT_SUPPORTED,
	bit_SCT_WRITE_SAME_FUNCTION_1_SUPPORTED,
	bit_SCT_WRITE_SAME_FUNCTION_2_SUPPORTED,
	bit_SCT_WRITE_SAME_FUNCTION_3_SUPPORTED,
	bit_SCT_WRITE_SAME_FUNCTION_101_SUPPORTED,
	bit_SCT_WRITE_SAME_FUNCTION_102_SUPPORTED,
	bit_SCT_WRITE_SAME_FUNCTION_103_SUPPORTED,
	bit_SCT_WRITE_SAME_SUPPORTED,
	bit_SECURITY_COUNT_EXPIRED,
	bit_SECURITY_ENABLED,
	bit_SECURITY_FROZEN,
	bit_SECURITY_LOCKED,
	bit_SECURITY_SUPPORTED,
	bit_SEND_AND_RECEIVE_QUEUED_COMMANDS_SUPPORTED,
	bit_SENSE_DATA_ENABLED,
	bit_SENSE_DATA_SUPPORTED,
	bit_SET_EPC_POWER_SOURCE_SUPPORTED,
	bit_SET_SECTOR_CONFIGURATION_SUPPORTED,
	bit_SETTING_RATE_BASIS_SUPPORTED,
	bit_SFF8447_REPORTING,
	bit_SINCE_POWER_ON_RATE_BASIS_SUPPORTED,
	bit_SMART,
	bit_SMART_ENABLED,
	bit_SMART_ERROR_LOGGING_SUPPORTED,
	bit_SMART_SELF_TEST_SUPPORTED,
	bit_SOFTWARE_SETTINGS_PRESERVATION_ENABLED,
	bit_SOFTWARE_SETTINGS_PRESERVATION_SUPPORTED,
	bit_SPIN_UP_SUPPORTED,
	bit_STREAMING_SUPPORTED,
	bit_SUCCESSFUL_NCQ_COMMAND_SENSE_DATA_ENABLED,
	bit_SUCCESSFUL_NCQ_COMMAND_SENSE_DATA_SUPPORTED,
	bit_TRIM_SUPPORTED,
	bit_TRUSTED_COMPUTING_SUPPORTED,
	bit_UDMA_MODE0_ENABLED,
	bit_UDMA_MODE0_SUPPORTED,
	bit_UDMA_MODE1_ENABLED,
	bit_UDMA_MODE1_SUPPORTED,
	bit_UDMA_MODE2_ENABLED,
	bit_UDMA_MODE2_SUPPORTED,
	bit_UDMA_MODE3_ENABLED,
	bit_UDMA_MODE3_SUPPORTED,
	bit_UDMA_MODE4_ENABLED,
	bit_UDMA_MODE4_SUPPORTED,
	bit_UDMA_MODE5_ENABLED,
	bit_UDMA_MODE5_SUPPORTED,
	bit_UDMA_MODE6_ENABLED,
	bit_UDMA_MODE6_SUPPORTED,
	bit_UNLOAD_SUPPORTED,
	bit_UNLOAD_WHILE_NCQ_COMMANDS_ARE_OUTSTANDING_SUPPORTED,
	bit_VOLATILE_WRITE_CACHE_ENABLED,
	bit_VOLATILE_WRITE_CACHE_SUPPORTED,
	bit_WRITE_BUFFER_DMA_SUPPORTED,
	bit_WRITE_BUFFER_SUPPORTED,
	bit_WRITE_FUA_EXT_SUPPORTED,
	bit_WRITE_UNCORRECTABLE_SUPPORTED,
	bit_WRV_ENABLED,
	bit_WRV_SUPPORTED,
	bit_ZERO_EXT_SUPPORTED,

	NUM_ATA_BITS
};

typedef unsigned long long	uint64;
typedef unsigned int		uint32;
typedef unsigned short		uint16;
typedef unsigned char		uint8;

typedef struct {
	uint64		ACCESSIBLE_CAPACITY			: 48;
	uint64		BUFFER_SIZE				: 63;

	unsigned	ALIGNMENT_ERROR_REPORTING		: 2;
	unsigned	CURRENT_SERIAL_ATA_SIGNAL_SPEED		: 3;
	unsigned	LOGICAL_SECTOR_OFFSET			: 14;
	unsigned	LOGICAL_TO_PHYSICAL_SECTOR_RELATIONSHIP	: 4;
	unsigned	MINIMUM_DEVSLP_ASSERTION_TIME		: 5;
	unsigned	MINIMUM_INACTIVE_TIME_IN_MILLISECONDS	: 10;
	unsigned	NOMINAL_FORM_FACTOR			: 4;
	unsigned	NORMAL_SECURITY_ERASE_TIME		: 15;
	unsigned	POWER_SOURCE				: 2;
	unsigned	QUEUE_DEPTH				: 5;
	unsigned	ZONED					: 2;

	uint32		ABO_MINIMUM_FRACTION;
	uint32		LOGICAL_SECTOR_SIZE;
	uint32		STREAM_GRANULARITY;
	uint32		UTILIZATION_A;
	uint32		UTILIZATION_B;
	uint32		WRV_MODE2_COUNT;
	uint32		WRV_MODE3_COUNT;

	uint16		ABO_MINIMUM_SUPPORTED_TIMELIMIT;
	uint16		ABO_RECOMMENDED_ABO_START_INTERVAL;
	uint16		CURRENT_HARDWARE_FEATURE_CONTROL_IDENTIFIER;
	uint16		DEVICE_MAINTENANCE_POLLING_TIME;
	uint16		DM_MAXIMUM_TRANSFER_SIZE;
	uint16		DM_MINIMUM_TRANSFER_SIZE;
	uint16		DMA_SECTOR_TIME;
	uint16		ENHANCED_SECURITY_ERASE_TIME;
	uint16		MASTER_PASSWORD_IDENTIFIER;
	uint16		MAX_PAGES_PER_DSM_COMMAND;
	uint16		MIN_MULTIWORD_CYCLE_TIME;
	uint16		MIN_PIO_TRANSFER_TIME_WITH_IORDY;
	uint16		MIN_PIO_TRANSFER_TIME_WITHOUT_IORDY;
	uint16		MINIMUM_INACTIVE_TIME;
	uint16		NOMINAL_MEDIA_ROTATION_RATE;
	uint16		PIO_SECTOR_TIME;
	uint16		RECOMMENDED_MULTIWORD_CYCLE_TIME;
	uint16		STREAM_ACCESS_LATENCY;
	uint16		STREAM_MIN_REQUEST_SIZE;
	uint16		SUPPORTED_HARDWARE_FEATURE_CONTROL_IDENTIFIER;
	uint16		TIME_SCHEDULED_FOR_DEVICE_MAINTENANCE;
	uint16		TIME_TO_PERFORMANCE_DEGRATION;

	uint8		ABO_STATUS;
	uint8		APM_LEVEL;
	uint8		DEVSLEEP_EXIT_TIMEOUT;
	uint8		FREE_FALL_SENSITIVITY;
	uint8		LOGICAL_BLOCK_MARKUPS_SUPPORTED;
	uint8		UTILIZATION_INTERVAL;
	uint8		UTILIZATION_TYPE;
	uint8		UTILIZATION_UNITS;
	uint8		WRV_MODE;

	char		ADDITIONAL_PRODUCT_IDENTIFIER[8];
	char		FIRMWARE_REVISION[8];
	char		MODEL_NUMBER[40];
	char		SERIAL_NUMBER[20];
	char		WORLD_WIDE_NAME[8];
} ATA_Fields;

extern	ATA_Fields	gATA_Fields;

#endif	/* _ATA_VARS_H */

