/******************************************************************************
** File Name: ../nvme_opcode.h
** Author:
** Creation Time: Wed Jan  3 23:46:55 2018
*/
#ifndef	_NVME_OPCODES_H
#define	_NVME_OPCODES_H

#define	NVME_OPC_ADMIN_DELETE_IOSQ	0x00
#define	NVME_OPC_ADMIN_CREATE_IOSQ	0x01
#define	NVME_OPC_ADMIN_GET_LOG_PAGE	0x02
#define	NVME_OPC_ADMIN_DELETE_IOCQ	0x04
#define	NVME_OPC_ADMIN_CREATE_IOCQ	0x05
#define	NVME_OPC_ADMIN_IDENTIFY		0x06
#define	NVME_OPC_ADMIN_ABORT		0x08
#define	NVME_OPC_ADMIN_SET_FEATURES	0x09
#define	NVME_OPC_ADMIN_GET_FEATURES	0x0A
#define	NVME_OPC_ADMIN_AER		0x0C
#define	NVME_OPC_ADMIN_NS_MANAGEMENT	0x0D
#define	NVME_OPC_ADMIN_FW_COMMIT	0x10
#define	NVME_OPC_ADMIN_FW_DOWNLOAD	0x11
#define	NVME_OPC_ADMIN_DST		0x14
#define	NVME_OPC_ADMIN_NS_ATTACHMENT	0x15
#define	NVME_OPC_ADMIN_KEEP_ALIVE	0x18
#define	NVME_OPC_ADMIN_DIRECTIVE_SND	0x19
#define	NVME_OPC_ADMIN_DIRECTIVE_RCV	0x1A
#define	NVME_OPC_ADMIN_NVME_MI_SND	0x1D
#define	NVME_OPC_ADMIN_NVME_MI_RCV	0x1E
#define	NVME_OPC_ADMIN_FORMAT_NVM	0x80
#define	NVME_OPC_ADMIN_SECURITY_SND	0x81
#define	NVME_OPC_ADMIN_SECURITY_RCV	0x82
#define	NVME_OPC_ADMIN_SANITIZE		0x84

#endif	/* _NVME_OPCODES_H */

